"""
Data Events Package - Modular event system for component coordination.

This package provides the event infrastructure for RingRift's distributed
training system. It was modularized in January 2026 to improve maintainability.

Components:
- event_types.py: DataEventType enum (~290 event types), DataEvent dataclass
- event_bus.py: EventBus class, singleton management, cross-process bridging
- emit.py: All emit_* convenience functions for publishing events

Usage:
    # Import core types
    from app.distributed.data_events import DataEventType, DataEvent, EventBus

    # Import event bus helpers
    from app.distributed.data_events import get_event_bus, reset_event_bus

    # Import cross-process configuration
    from app.distributed.data_events import CROSS_PROCESS_EVENT_TYPES

    # Import emit functions
    from app.distributed.data_events import emit_training_completed

Note: The unified event router is preferred for new code:
    from app.coordination.event_router import get_router
"""

# Core types
from .event_types import (
    DataEventType,
    DataEvent,
)

# Event bus
from .event_bus import (
    EventBus,
    EventCallback,
    get_event_bus,
    reset_event_bus,
    CROSS_PROCESS_EVENT_TYPES,
)

# Emit functions
from .emit import (
    emit_backpressure_activated,
    emit_backpressure_released,
    emit_batch_dispatched,
    emit_batch_scheduled,
    emit_budget_alert,
    emit_budget_exceeded,
    emit_capacity_low,
    emit_capacity_restored,
    emit_checkpoint_loaded,
    emit_checkpoint_saved,
    emit_cluster_capacity_changed,
    emit_cmaes_triggered,
    emit_curriculum_advanced,
    emit_curriculum_rebalanced,
    emit_curriculum_rollback_completed,
    emit_daemon_crash_loop_detected,
    emit_daemon_permanently_failed,
    emit_daemon_started,
    emit_daemon_status_changed,
    emit_daemon_stopped,
    emit_data_event,
    emit_data_fresh,
    emit_data_stale,
    emit_data_sync_completed,
    emit_data_sync_failed,
    emit_data_sync_started,
    emit_deadlock_detected,
    emit_disk_space_low,
    emit_elo_updated,
    emit_elo_updated_sync,
    emit_elo_velocity_changed,
    emit_error,
    emit_evaluation_completed,
    emit_evaluation_failed,
    emit_evaluation_started,
    emit_exploration_boost,
    emit_health_check_failed,
    emit_health_check_passed,
    emit_host_offline,
    emit_host_online,
    emit_hyperparameter_updated,
    emit_idle_resource_detected,
    emit_job_spawn_failed,
    emit_job_spawn_verified,
    emit_leader_elected,
    emit_leader_heartbeat_missing,
    emit_leader_lease_expired,
    emit_leader_lost,
    emit_model_distribution_complete,
    emit_model_distribution_failed,
    emit_model_distribution_started,
    emit_model_promoted,
    emit_nas_triggered,
    emit_new_games,
    emit_node_capacity_updated,
    emit_node_capacity_updated_sync,
    emit_node_incompatible_with_workload,
    emit_node_overloaded,
    emit_node_provision_failed,
    emit_node_provisioned,
    emit_node_recovered,
    emit_node_retired,
    emit_node_suspect,
    emit_node_unhealthy,
    emit_orphan_games_detected,
    emit_orphan_games_registered,
    emit_orphan_game_prevented,
    emit_game_save_failed,
    emit_p2p_cluster_healthy,
    emit_p2p_cluster_unhealthy,
    emit_p2p_restarted,
    emit_parity_failure_rate_changed,
    emit_plateau_detected,
    emit_promotion_candidate,
    emit_promotion_failed,
    emit_promotion_rejected,
    emit_promotion_started,
    emit_quality_check_requested,
    emit_quality_degraded,
    emit_quality_score_updated,
    emit_selfplay_allocation_updated,
    emit_selfplay_complete,
    emit_selfplay_rate_changed,
    emit_selfplay_target_updated,
    emit_sync_stalled,
    emit_sync_triggered,
    emit_task_abandoned,
    emit_task_completed,
    emit_task_failed,
    emit_task_heartbeat,
    emit_task_orphaned,
    emit_task_spawned,
    emit_tier_promotion,
    emit_training_completed,
    emit_training_early_stopped,
    emit_training_failed,
    emit_training_loss_anomaly,
    emit_training_loss_trend,
    emit_training_started,
    emit_training_threshold,
    emit_weight_updated,
)

__all__ = [
    # Core types
    "DataEventType",
    "DataEvent",
    # Event bus
    "EventBus",
    "EventCallback",
    "get_event_bus",
    "reset_event_bus",
    "CROSS_PROCESS_EVENT_TYPES",
    # Emit functions
    "emit_backpressure_activated",
    "emit_backpressure_released",
    "emit_batch_dispatched",
    "emit_batch_scheduled",
    "emit_budget_alert",
    "emit_budget_exceeded",
    "emit_capacity_low",
    "emit_capacity_restored",
    "emit_checkpoint_loaded",
    "emit_checkpoint_saved",
    "emit_cluster_capacity_changed",
    "emit_cmaes_triggered",
    "emit_curriculum_advanced",
    "emit_curriculum_rebalanced",
    "emit_curriculum_rollback_completed",
    "emit_daemon_crash_loop_detected",
    "emit_daemon_permanently_failed",
    "emit_daemon_started",
    "emit_daemon_status_changed",
    "emit_daemon_stopped",
    "emit_data_event",
    "emit_data_fresh",
    "emit_data_stale",
    "emit_data_sync_completed",
    "emit_data_sync_failed",
    "emit_data_sync_started",
    "emit_deadlock_detected",
    "emit_disk_space_low",
    "emit_elo_updated",
    "emit_elo_updated_sync",
    "emit_elo_velocity_changed",
    "emit_error",
    "emit_evaluation_completed",
    "emit_evaluation_failed",
    "emit_evaluation_started",
    "emit_exploration_boost",
    "emit_health_check_failed",
    "emit_health_check_passed",
    "emit_host_offline",
    "emit_host_online",
    "emit_hyperparameter_updated",
    "emit_idle_resource_detected",
    "emit_job_spawn_failed",
    "emit_job_spawn_verified",
    "emit_leader_elected",
    "emit_leader_heartbeat_missing",
    "emit_leader_lease_expired",
    "emit_leader_lost",
    "emit_model_distribution_complete",
    "emit_model_distribution_failed",
    "emit_model_distribution_started",
    "emit_model_promoted",
    "emit_nas_triggered",
    "emit_new_games",
    "emit_node_capacity_updated",
    "emit_node_capacity_updated_sync",
    "emit_node_incompatible_with_workload",
    "emit_node_overloaded",
    "emit_node_provision_failed",
    "emit_node_provisioned",
    "emit_node_recovered",
    "emit_node_retired",
    "emit_node_suspect",
    "emit_node_unhealthy",
    "emit_orphan_games_detected",
    "emit_orphan_games_registered",
    "emit_orphan_game_prevented",
    "emit_game_save_failed",
    "emit_p2p_cluster_healthy",
    "emit_p2p_cluster_unhealthy",
    "emit_p2p_restarted",
    "emit_parity_failure_rate_changed",
    "emit_plateau_detected",
    "emit_promotion_candidate",
    "emit_promotion_failed",
    "emit_promotion_rejected",
    "emit_promotion_started",
    "emit_quality_check_requested",
    "emit_quality_degraded",
    "emit_quality_score_updated",
    "emit_selfplay_allocation_updated",
    "emit_selfplay_complete",
    "emit_selfplay_rate_changed",
    "emit_selfplay_target_updated",
    "emit_sync_stalled",
    "emit_sync_triggered",
    "emit_task_abandoned",
    "emit_task_completed",
    "emit_task_failed",
    "emit_task_heartbeat",
    "emit_task_orphaned",
    "emit_task_spawned",
    "emit_tier_promotion",
    "emit_training_completed",
    "emit_training_early_stopped",
    "emit_training_failed",
    "emit_training_loss_anomaly",
    "emit_training_loss_trend",
    "emit_training_started",
    "emit_training_threshold",
    "emit_weight_updated",
]
