"""Data Quality Sentinel (DQS) — validates training data quality between export and training.

Computes statistical fingerprints of NPZ training data, compares against
historical iterations, and produces a PASS/WARN/CRITICAL verdict to prevent
low-quality or degenerate data from entering the training pipeline.

Usage from minimal_alphazero_loop.py:
    from scripts.lib.data_quality_sentinel import check_data_quality

    verdict = check_data_quality(str(train_npz), work_dir=str(wdir))
    if verdict.critical:
        logger.error(f"DATA QUALITY CRITICAL: {verdict.summary}")
        consec_failures += 1; continue
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)

HISTORY_FILENAME = "data_quality_history.jsonl"


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class DataFingerprint:
    n_samples: int
    n_channels: int
    feature_means: list[float]  # per-channel
    feature_stds: list[float]   # per-channel
    policy_entropy_median: float
    policy_entropy_p10: float
    policy_entropy_p90: float
    value_mean: float
    value_std: float
    checksum: float  # sum of all features for quick comparison


@dataclass
class QualityVerdict:
    passed: bool
    critical: bool
    warnings: list[str]
    summary: str
    fingerprint: DataFingerprint


# ---------------------------------------------------------------------------
# 1. NPZ Statistical Fingerprint
# ---------------------------------------------------------------------------

def _compute_policy_entropy(policy: np.ndarray) -> np.ndarray:
    """Compute per-sample Shannon entropy (bits) over the policy distribution."""
    # Clamp to avoid log(0)
    p = np.clip(policy, 1e-12, 1.0)
    entropy = -np.sum(p * np.log2(p), axis=-1)
    return entropy


def compute_fingerprint(npz_path: str, *, mmap: bool = True) -> DataFingerprint:
    """Load an NPZ file and compute its statistical fingerprint.

    Uses mmap_mode='r' by default for speed on large files.
    Trusted local training data generated by the pipeline.
    """
    mode = "r" if mmap else None
    # Training NPZ files are trusted local data generated by our pipeline.
    # allow_pickle is needed for backward compat with older NPZ files that
    # may contain object arrays (board_type, metadata).
    data = np.load(npz_path, mmap_mode=mode, allow_pickle=True)  # trusted local training data

    features = data["features"]
    n_samples = features.shape[0]
    n_channels = features.shape[1] if features.ndim >= 2 else 0

    # Per-channel statistics — operate on float32 to keep fast
    if features.ndim >= 2:
        # Reshape to (n_samples, n_channels, -1) then take mean/std per channel
        flat = features.reshape(n_samples, n_channels, -1)
        ch_means = flat.mean(axis=(0, 2)).astype(np.float64).tolist()
        ch_stds = flat.std(axis=(0, 2)).astype(np.float64).tolist()
    else:
        ch_means = [float(features.mean())]
        ch_stds = [float(features.std())]

    # Policy entropy — handle both dense and sparse policy formats.
    # Dense: "policy" array of shape (N, action_space)
    # Sparse: "policy_indices" + "policy_values" (object arrays of variable-length per sample)
    policy_key = "policy" if "policy" in data.files else "policies"
    if policy_key in data.files:
        policy = np.asarray(data[policy_key], dtype=np.float32)
        if policy.ndim >= 2:
            entropy = _compute_policy_entropy(policy)
        else:
            entropy = np.array([0.0])
    elif "policy_values" in data.files:
        # Sparse policy format: compute entropy per sample from variable-length value arrays
        pv = data["policy_values"]
        ent_list = []
        for i in range(min(len(pv), 2000)):  # sample up to 2000 for speed
            vals = np.asarray(pv[i], dtype=np.float64)
            vals = vals[vals > 0]
            if len(vals) > 0:
                vals = vals / vals.sum()  # renormalize
                ent_list.append(float(-np.sum(vals * np.log2(vals + 1e-12))))
            else:
                ent_list.append(0.0)
        entropy = np.array(ent_list) if ent_list else np.array([0.0])
    else:
        entropy = np.array([0.0])

    ent_median = float(np.median(entropy))
    ent_p10 = float(np.percentile(entropy, 10))
    ent_p90 = float(np.percentile(entropy, 90))

    # Value target statistics
    value_key = "value" if "value" in data.files else "values"
    if value_key in data.files:
        values = np.asarray(data[value_key], dtype=np.float64)
        v_mean = float(values.mean())
        v_std = float(values.std())
    else:
        v_mean = 0.0
        v_std = 0.0

    # Quick checksum: sum of all feature values (fast on mmap)
    checksum = float(features.sum())

    return DataFingerprint(
        n_samples=n_samples,
        n_channels=n_channels,
        feature_means=ch_means,
        feature_stds=ch_stds,
        policy_entropy_median=ent_median,
        policy_entropy_p10=ent_p10,
        policy_entropy_p90=ent_p90,
        value_mean=v_mean,
        value_std=v_std,
        checksum=checksum,
    )


# ---------------------------------------------------------------------------
# 2. Cross-Iteration Comparison
# ---------------------------------------------------------------------------

@dataclass
class ComparisonResult:
    identical_data: bool  # Feature delta < threshold vs all recent
    low_diversity: bool   # Policy entropy too low
    no_value_variance: bool  # Value targets are constant
    high_draw_rate: bool  # (placeholder — detectable from value distribution)
    details: list[str] = field(default_factory=list)


def _load_history(work_dir: str, max_entries: int = 5) -> list[DataFingerprint]:
    """Load last N fingerprints from the JSONL history file."""
    history_path = Path(work_dir) / HISTORY_FILENAME
    if not history_path.exists():
        return []
    entries: list[DataFingerprint] = []
    try:
        for line in history_path.read_text().strip().split("\n"):
            if not line.strip():
                continue
            d = json.loads(line)
            fp = d.get("fingerprint", d)
            entries.append(DataFingerprint(**{
                k: fp[k] for k in DataFingerprint.__dataclass_fields__
                if k in fp
            }))
    except Exception as e:
        logger.warning("Failed to load DQS history: %s", e)
        return []
    return entries[-max_entries:]


def _save_fingerprint(work_dir: str, fp: DataFingerprint) -> None:
    """Append a fingerprint to the JSONL history file."""
    history_path = Path(work_dir) / HISTORY_FILENAME
    history_path.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "fingerprint": asdict(fp),
    }
    with open(history_path, "a") as f:
        f.write(json.dumps(entry) + "\n")


def compare_with_history(
    fp: DataFingerprint,
    history: list[DataFingerprint],
    *,
    delta_threshold: float = 0.01,
) -> ComparisonResult:
    """Compare current fingerprint against recent history."""
    details: list[str] = []
    identical = False
    low_diversity = fp.policy_entropy_median < 1.0
    no_value_var = fp.value_std < 0.01
    high_draws = False  # Approximated: if value mean ~0 and std ~0 it's all draws

    if history:
        # Check if features are near-identical to ANY recent iteration
        for i, prev in enumerate(history):
            if len(fp.feature_means) != len(prev.feature_means):
                continue
            deltas = [
                abs(a - b)
                for a, b in zip(fp.feature_means, prev.feature_means)
            ]
            max_delta = max(deltas) if deltas else 1.0
            if max_delta < delta_threshold:
                identical = True
                details.append(
                    f"Features near-identical to history[-{len(history)-i}] "
                    f"(max delta={max_delta:.6f})"
                )
                break

    if low_diversity:
        details.append(
            f"Low policy entropy: median={fp.policy_entropy_median:.3f} bits"
        )

    if no_value_var:
        details.append(f"Value targets have no variance: std={fp.value_std:.6f}")

    # Approximate draw rate check: in 2-player, value ~0 means draw
    # In multiplayer, uniform distribution means draws
    if fp.value_std < 0.05 and abs(fp.value_mean) < 0.1:
        high_draws = True
        details.append(
            f"Possible high draw rate: value_mean={fp.value_mean:.4f}, "
            f"value_std={fp.value_std:.4f}"
        )

    return ComparisonResult(
        identical_data=identical,
        low_diversity=low_diversity,
        no_value_variance=no_value_var,
        high_draw_rate=high_draws,
        details=details,
    )


# ---------------------------------------------------------------------------
# 3. Quality Verdict
# ---------------------------------------------------------------------------

def compute_verdict(
    fp: DataFingerprint,
    comparison: ComparisonResult,
) -> QualityVerdict:
    """Aggregate fingerprint and comparison into PASS/WARN/CRITICAL."""
    warnings: list[str] = []
    critical = False

    # Policy entropy checks
    if fp.policy_entropy_median < 0.5:
        critical = True
        warnings.append(
            f"CRITICAL: Policy entropy extremely low "
            f"({fp.policy_entropy_median:.3f} bits < 0.5)"
        )
    elif fp.policy_entropy_median < 1.5:
        warnings.append(
            f"Policy entropy low ({fp.policy_entropy_median:.3f} bits < 1.5)"
        )

    # Feature channel-wise variance check
    if fp.feature_stds and all(s < 0.001 for s in fp.feature_stds):
        critical = True
        warnings.append(
            "CRITICAL: All feature channels have near-zero variance "
            f"(max std={max(fp.feature_stds):.6f})"
        )

    # Cross-iteration identical data
    if comparison.identical_data:
        critical = True
        warnings.append(
            "CRITICAL: Training data is near-identical to a recent iteration"
        )

    # Value target variance
    if comparison.no_value_variance and not critical:
        warnings.append(
            f"Value target variance very low (std={fp.value_std:.6f})"
        )

    # Build summary
    if critical:
        summary = "CRITICAL — " + "; ".join(
            w for w in warnings if w.startswith("CRITICAL")
        )
    elif warnings:
        summary = f"WARN ({len(warnings)} issues) — " + "; ".join(warnings)
    else:
        summary = (
            f"PASS — {fp.n_samples} samples, {fp.n_channels}ch, "
            f"entropy={fp.policy_entropy_median:.2f} bits"
        )

    return QualityVerdict(
        passed=not critical,
        critical=critical,
        warnings=warnings,
        summary=summary,
        fingerprint=fp,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_data_quality(
    npz_path: str,
    *,
    work_dir: Optional[str] = None,
    save_history: bool = True,
) -> QualityVerdict:
    """Run the full DQS pipeline: fingerprint -> compare -> verdict.

    Args:
        npz_path: Path to the NPZ training file.
        work_dir: Directory for storing fingerprint history (JSONL).
                  Defaults to parent directory of npz_path.
        save_history: Whether to append the fingerprint to history.

    Returns:
        QualityVerdict with passed/critical flags and warnings.
    """
    t0 = time.time()

    if work_dir is None:
        work_dir = str(Path(npz_path).parent)

    fp = compute_fingerprint(npz_path)
    history = _load_history(work_dir)
    comparison = compare_with_history(fp, history)
    verdict = compute_verdict(fp, comparison)

    if save_history:
        _save_fingerprint(work_dir, fp)

    elapsed = time.time() - t0
    logger.info(
        "DQS: %s (%d samples, %.2f bits entropy, %.3fs)",
        "CRITICAL" if verdict.critical else ("WARN" if verdict.warnings else "PASS"),
        fp.n_samples,
        fp.policy_entropy_median,
        elapsed,
    )

    return verdict
