import { z } from 'zod';
import { Request } from 'express';

// ====================================================================
// CONSTANTS
// ====================================================================

/** Maximum length for user-generated content to prevent DoS via large payloads */
export const MAX_USER_CONTENT_LENGTH = 10000;

/** Maximum username length */
export const MAX_USERNAME_LENGTH = 32;

/** Minimum username length */
export const MIN_USERNAME_LENGTH = 3;

/** Maximum email length */
export const MAX_EMAIL_LENGTH = 255;

/** Minimum password length */
export const MIN_PASSWORD_LENGTH = 8;

/** Maximum password length */
export const MAX_PASSWORD_LENGTH = 128;

/** Maximum chat message length */
export const MAX_CHAT_MESSAGE_LENGTH = 500;

// ====================================================================
// COMMON REUSABLE SCHEMAS
// ====================================================================

/**
 * UUID v4 validation schema. Used for entity IDs (games, users, etc.)
 */
export const UUIDSchema = z.string().uuid('Invalid ID format').min(1, 'ID is required');

/**
 * Safe string schema that strips dangerous characters for XSS prevention.
 * Use for user-generated content that will be displayed.
 */
export const SafeStringSchema = z.string().transform((val) => sanitizeString(val));

/**
 * Pagination query parameters schema.
 * Used across list endpoints for consistent pagination handling.
 */
export const PaginationQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
  sortBy: z.string().max(50).optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
});

export type PaginationQueryInput = z.infer<typeof PaginationQuerySchema>;

/**
 * Game ID URL parameter validation.
 *
 * Accepts both legacy UUID-style IDs and the CUID-style string IDs
 * generated by Prisma for the Game model. This ensures that any ID
 * returned by POST /api/games can be used with GET /api/games/:gameId
 * while still rejecting obviously invalid formats.
 */
const GameIdValueSchema = z.union([
  UUIDSchema,
  z
    .string()
    .regex(/^c[0-9a-z]{24}$/i, 'Invalid ID format')
    .min(1, 'ID is required'),
]);

export const GameIdParamSchema = z.object({
  gameId: GameIdValueSchema,
});

export type GameIdParamInput = z.infer<typeof GameIdParamSchema>;

/**
 * Game listing query parameters schema.
 * Used for filtering games in list/lobby endpoints.
 */
export const GameListingQuerySchema = z.object({
  status: z.enum(['waiting', 'active', 'completed', 'abandoned', 'paused']).optional(),
  boardType: z.enum(['square8', 'square19', 'hexagonal']).optional(),
  maxPlayers: z.coerce.number().int().min(2).max(4).optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

export type GameListingQueryInput = z.infer<typeof GameListingQuerySchema>;

/**
 * User search query parameters schema.
 */
export const UserSearchQuerySchema = z.object({
  q: z
    .string()
    .min(1, 'Search query is required')
    .max(100, 'Search query too long')
    .transform((val) => sanitizeString(val)),
  limit: z.coerce.number().int().min(1).max(50).default(10),
});

export type UserSearchQueryInput = z.infer<typeof UserSearchQuerySchema>;

/**
 * Time period filter for leaderboard queries.
 * - 'all': All time (default)
 * - 'week': Last 7 days
 * - 'month': Last 30 days
 * - 'year': Last 365 days
 */
export const TimePeriodSchema = z.enum(['all', 'week', 'month', 'year']).default('all');

/**
 * Board type filter for leaderboard queries.
 */
export const BoardTypeFilterSchema = z
  .enum(['all', 'square8', 'square19', 'hexagonal'])
  .default('all');

/**
 * Leaderboard query parameters schema.
 * Supports filtering by board type and time period.
 */
export const LeaderboardQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(50),
  offset: z.coerce.number().int().min(0).default(0),
  boardType: BoardTypeFilterSchema.optional(),
  timePeriod: TimePeriodSchema.optional(),
});

export type LeaderboardQueryInput = z.infer<typeof LeaderboardQuerySchema>;
export type TimePeriod = z.infer<typeof TimePeriodSchema>;
export type BoardTypeFilter = z.infer<typeof BoardTypeFilterSchema>;

// ====================================================================
// SANITIZATION UTILITIES
// ====================================================================

/**
 * Sanitizes a string by removing or escaping potentially dangerous characters.
 * This provides defense-in-depth against XSS even when content is properly escaped on output.
 *
 * @param input - The raw user input string
 * @returns Sanitized string safe for storage
 */
export function sanitizeString(input: string): string {
  if (typeof input !== 'string') {
    return '';
  }

  return (
    input
      // Remove null bytes
      .replace(/\0/g, '')
      // Normalize Unicode to prevent homoglyph attacks
      .normalize('NFC')
      // Trim excessive whitespace
      .trim()
  );
}

/**
 * Sanitizes user-generated content that may be displayed in HTML contexts.
 * Escapes HTML entities to prevent XSS attacks.
 *
 * NOTE: This should be used as a defense-in-depth measure. The primary XSS
 * prevention should be proper output encoding by the rendering layer (React, etc.)
 *
 * @param input - The raw user input string
 * @returns HTML-escaped string
 */
export function sanitizeHtmlContent(input: string): string {
  if (typeof input !== 'string') {
    return '';
  }

  const htmlEntities: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#x27;',
    '/': '&#x2F;',
    '`': '&#x60;',
    '=': '&#x3D;',
  };

  return sanitizeString(input).replace(/[&<>"'`=/]/g, (char) => htmlEntities[char] || char);
}

/**
 * Creates a schema for user-generated content with XSS sanitization.
 *
 * @param maxLength - Maximum allowed length (default: MAX_CHAT_MESSAGE_LENGTH)
 * @param minLength - Minimum required length (default: 1)
 */
export function createSanitizedStringSchema(
  maxLength: number = MAX_CHAT_MESSAGE_LENGTH,
  minLength: number = 1
) {
  return z
    .string()
    .min(minLength)
    .max(maxLength)
    .transform((val) => sanitizeString(val.trim()));
}

// ====================================================================
// GAME SCHEMAS
// ====================================================================

// Position validation
export const PositionSchema = z.object({
  x: z.number().int().min(0),
  y: z.number().int().min(0),
  z: z.number().int().min(0).optional(),
});

// Move validation
// NOTE:
// - This is the simplified wire-level move payload used by WebSockets/HTTP
//   (`MovePayload` in src/shared/types/game.ts), not the full internal Move.
// - It intentionally omits decision-only move types such as
//   'process_line', 'choose_line_reward', 'process_territory_region', and
//   'eliminate_rings_from_stack', which are carried by separate
//   player-choice/decision payloads rather than the generic player_move
//   channel.
export const MoveSchema = z.object({
  moveType: z.enum([
    'place_ring',
    'move_ring',
    'build_stack',
    'move_stack',
    'overtaking_capture',
    'continue_capture_segment',
    'skip_placement',
    'swap_sides',
    'line_formation',
    'territory_claim',
    'recovery_slide', // RR-CANON-R110–R115: marker recovery action
    'skip_recovery', // RR-CANON-R115: explicit recovery skip
  ]),
  position: z.union([
    z.string(),
    z.object({
      from: PositionSchema.optional(),
      to: PositionSchema,
    }),
  ]),
  moveNumber: z.number().int().min(1).optional(),
});

export type MoveInput = z.infer<typeof MoveSchema>;

// Game creation validation
// NOTE: The shape of this schema is intentionally kept in sync with
// the shared CreateGameRequest/AiOpponentsConfig types in
// src/shared/types/game.ts. If you add fields here, update those
// types as well so the client, server, and validation layer share
// a single mental model of the create-game payload.
export const CreateGameSchema = z.object({
  boardType: z.enum(['square8', 'square19', 'hexagonal']),
  timeControl: z.object({
    type: z.enum(['blitz', 'rapid', 'classical']),
    initialTime: z.number().min(60).max(7200), // 1 minute to 2 hours
    increment: z.number().min(0).max(60), // Max 60 seconds increment
  }),
  isRated: z.boolean().default(true),
  isPrivate: z.boolean().default(false),
  maxPlayers: z.number().min(2).max(4).default(2),
  aiOpponents: z
    .object({
      count: z.number().min(0).max(3),
      difficulty: z.array(z.number().min(1).max(10)),
      mode: z.enum(['local_heuristic', 'service']).optional(),
      aiType: z.enum(['random', 'heuristic', 'minimax', 'mcts', 'descent']).optional(),
      aiTypes: z.array(z.enum(['random', 'heuristic', 'minimax', 'mcts', 'descent'])).optional(),
    })
    .optional(),
  seed: z.number().int().min(0).max(0x7fffffff).optional(), // Optional RNG seed for deterministic games
  // Optional per-game rules configuration. When omitted, hosts should apply
  // their own defaults (e.g., enabling the pie rule for 2-player games).
  rulesOptions: z
    .object({
      swapRuleEnabled: z.boolean().optional(),
      // (future) p2DoubleTurnMode?: 'off' | 'sequential' | 'mega';
      // (future) p1NoFirstTurnCaptures?: boolean;
      // (future) p1NoFirstTurnLines?: boolean;
      // (future) openingMode?: 'standard' | 'randomized_openings' | 'opening_book';
      // (future) ringHandicapByPlayer?: Record<number, number>;
      // (future) territoryTemplateId?: string;
    })
    .optional(),
  /**
   * When true, marks this game as part of an explicit AI difficulty
   * calibration run (for example, Square‑8 2-player D2/D4/D6/D8 tests).
   */
  isCalibrationGame: z.boolean().optional(),
  /**
   * Primary AI difficulty tier being calibrated for this game (1–10). For
   * calibration games with multiple AI opponents, this should represent the
   * primary target tier (usually the strongest AI).
   */
  calibrationDifficulty: z.number().min(1).max(10).optional(),
});

// Convenience alias so server code can use a single source of truth
// for the parsed payload type.
export type CreateGameInput = z.infer<typeof CreateGameSchema>;

// User registration validation
export const RegisterSchema = z
  .object({
    username: z
      .string()
      .min(MIN_USERNAME_LENGTH, `Username must be at least ${MIN_USERNAME_LENGTH} characters`)
      .max(MAX_USERNAME_LENGTH, `Username must be at most ${MAX_USERNAME_LENGTH} characters`)
      .regex(
        /^[a-zA-Z0-9_-]+$/,
        'Username can only contain letters, numbers, underscores, and hyphens'
      ),
    email: z
      .string()
      .email('Invalid email address')
      .max(255, 'Email must be at most 255 characters'),
    password: z
      .string()
      .min(8, 'Password must be at least 8 characters')
      .max(128, 'Password must be at most 128 characters')
      .regex(
        /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/,
        'Password must contain at least one lowercase letter, one uppercase letter, and one number'
      ),
    confirmPassword: z.string(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords don't match",
    path: ['confirmPassword'],
  });

// User login validation
export const LoginSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(1, 'Password is required'),
  rememberMe: z.boolean().optional(),
});

// Auth token / email verification payloads
export const RefreshTokenSchema = z.object({
  refreshToken: z.string().min(1, 'Refresh token required'),
});

export const VerifyEmailSchema = z.object({
  token: z.string().min(1, 'Verification token required'),
});

export const ForgotPasswordSchema = z.object({
  email: z.string().email('Invalid email address'),
});

export const ResetPasswordSchema = z.object({
  token: z.string().min(1, 'Token is required'),
  newPassword: z
    .string()
    .min(8, 'Password must be at least 8 characters long')
    .max(128, 'Password must be at most 128 characters'),
});

// Profile update validation
export const UpdateProfileSchema = z.object({
  username: z
    .string()
    .min(MIN_USERNAME_LENGTH, `Username must be at least ${MIN_USERNAME_LENGTH} characters`)
    .max(MAX_USERNAME_LENGTH, `Username must be at most ${MAX_USERNAME_LENGTH} characters`)
    .regex(
      /^[a-zA-Z0-9_-]+$/,
      'Username can only contain letters, numbers, underscores, and hyphens'
    )
    .optional(),
  email: z
    .string()
    .email('Invalid email address')
    .max(255, 'Email must be at most 255 characters')
    .optional(),
  preferences: z
    .object({
      boardTheme: z.string().optional(),
      pieceStyle: z.string().optional(),
      soundEnabled: z.boolean().optional(),
      animationsEnabled: z.boolean().optional(),
      autoPromoteQueen: z.boolean().optional(),
      showCoordinates: z.boolean().optional(),
      highlightLastMove: z.boolean().optional(),
      confirmMoves: z.boolean().optional(),
      timeZone: z.string().optional(),
      language: z.string().optional(),
    })
    .optional(),
});

// Password change validation
export const ChangePasswordSchema = z
  .object({
    currentPassword: z.string().min(1, 'Current password is required'),
    newPassword: z
      .string()
      .min(8, 'Password must be at least 8 characters')
      .max(128, 'Password must be at most 128 characters')
      .regex(
        /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/,
        'Password must contain at least one lowercase letter, one uppercase letter, and one number'
      ),
    confirmPassword: z.string(),
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    message: "Passwords don't match",
    path: ['confirmPassword'],
  });

// Chat message validation
export const ChatMessageSchema = z.object({
  gameId: z.string().uuid('Invalid game ID'),
  content: z
    .string()
    .min(1, 'Message cannot be empty')
    .max(MAX_CHAT_MESSAGE_LENGTH, `Message must be at most ${MAX_CHAT_MESSAGE_LENGTH} characters`)
    .trim(),
  type: z.enum(['game', 'spectator', 'private']).default('game'),
  recipientId: z.string().uuid().optional(),
});

// Matchmaking preferences validation
export const MatchmakingPreferencesSchema = z.object({
  boardType: z.enum(['square8', 'square19', 'hexagonal']),
  timeControl: z
    .object({
      min: z.number().min(60).max(7200),
      max: z.number().min(60).max(7200),
    })
    .refine((data) => data.min <= data.max, {
      message: 'Minimum time must be less than or equal to maximum time',
    }),
  ratingRange: z
    .object({
      min: z.number().min(100).max(3000),
      max: z.number().min(100).max(3000),
    })
    .refine((data) => data.min <= data.max, {
      message: 'Minimum rating must be less than or equal to maximum rating',
    }),
  allowAI: z.boolean().default(false),
});

// Tournament creation validation
export const CreateTournamentSchema = z
  .object({
    name: z
      .string()
      .min(3, 'Tournament name must be at least 3 characters')
      .max(100, 'Tournament name must be at most 100 characters'),
    format: z.enum(['single_elimination', 'double_elimination', 'round_robin', 'swiss']),
    boardType: z.enum(['square8', 'square19', 'hexagonal']),
    maxParticipants: z.number().min(4).max(256),
    timeControl: z.object({
      initialTime: z.number().min(60).max(7200),
      increment: z.number().min(0).max(60),
    }),
    isRated: z.boolean().default(true),
    entryFee: z.number().min(0).optional(),
    prizePool: z.number().min(0).optional(),
    startsAt: z.date().min(new Date(), 'Tournament start time must be in the future'),
    registrationDeadline: z.date().optional(),
  })
  .refine(
    (data) => {
      if (data.registrationDeadline) {
        return data.registrationDeadline <= data.startsAt;
      }
      return true;
    },
    {
      message: 'Registration deadline must be before tournament start time',
      path: ['registrationDeadline'],
    }
  );

// WebSocket event validation
export const SocketEventSchema = z.object({
  event: z.string().min(1),
  data: z.unknown(),
  timestamp: z.date().optional(),
});

// Game state validation (for API responses)
// NOTE: This is a partial view of GameState, suitable for validating
// API responses. It does not attempt to mirror the full internal
// GameState shape used by GameEngine.
export const GameStateSchema = z.object({
  id: z.string().uuid(),
  boardType: z.enum(['square8', 'square19', 'hexagonal']),
  players: z.array(
    z.object({
      id: z.string().uuid(),
      username: z.string(),
      type: z.enum(['human', 'ai']),
      playerNumber: z.number().int().min(1).max(4),
      rating: z.number().optional(),
      isReady: z.boolean(),
      timeRemaining: z.number(),
      aiDifficulty: z.number().min(1).max(10).optional(),
    })
  ),
  currentPhase: z.enum([
    'ring_placement',
    'movement',
    'capture',
    'chain_capture',
    'line_processing',
    'territory_processing',
  ]),
  currentPlayer: z.number().int().min(1).max(4),
  gameStatus: z.enum(['waiting', 'active', 'finished', 'paused', 'abandoned', 'completed']),
  winner: z.number().int().min(1).max(4).optional(),
  isRated: z.boolean(),
  maxPlayers: z.number().min(2).max(4),
});

export type GameStatePayload = z.infer<typeof GameStateSchema>;

// Pagination validation
export const PaginationSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(20),
  sortBy: z.string().optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
});

// Search validation
export const SearchSchema = z.object({
  query: z.string().min(1).max(100),
  type: z.enum(['users', 'games', 'tournaments']).optional(),
  filters: z.record(z.string(), z.unknown()).optional(),
});

// File upload validation
export const FileUploadSchema = z.object({
  filename: z.string().min(1).max(255),
  mimetype: z.string().regex(/^image\/(jpeg|png|gif|webp)$/, 'Only image files are allowed'),
  size: z.number().max(5 * 1024 * 1024, 'File size must be less than 5MB'),
});

// API response validation helpers
export const createSuccessResponse = <T>(data: T) => ({
  success: true,
  data,
  timestamp: new Date(),
});

export const createErrorResponse = (message: string, code?: string, details?: unknown) => ({
  success: false,
  error: {
    message,
    code,
    details,
    timestamp: new Date(),
  },
});

// Validation middleware helper types
export type ValidationSchema = z.ZodSchema<unknown>;
export type ValidatedRequest<T> = Request & { validatedData: T };

// Common validation patterns
export const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const USERNAME_REGEX = /^[a-zA-Z0-9_-]+$/;
export const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/;

// Validation error types
export class ValidationError extends Error {
  constructor(
    message: string,
    public field?: string,
    public code?: string
  ) {
    super(message);
    this.name = 'ValidationError';
  }
}

export class AuthenticationError extends Error {
  constructor(message: string = 'Authentication required') {
    super(message);
    this.name = 'AuthenticationError';
  }
}

export class AuthorizationError extends Error {
  constructor(message: string = 'Insufficient permissions') {
    super(message);
    this.name = 'AuthorizationError';
  }
}
