#!/usr/bin/env bash
# Deploy ringrift-training.service to Lambda GH200 nodes.
# Creates /etc/ringrift/training.conf with per-node hyperparameters,
# installs the systemd service, and starts it.
#
# Usage:
#   ./scripts/deploy_training_service.sh [--only NODE_NAME] [--dry-run] [--restart]
set -euo pipefail

SSH_KEY="${HOME}/.ssh/id_cluster"
SSH_OPTS=(-o IdentitiesOnly=yes -i "$SSH_KEY" -o ConnectTimeout=10 -o StrictHostKeyChecking=no)
SERVICE_FILE="config/systemd/ringrift-training.service"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AI_DIR="$(dirname "$SCRIPT_DIR")"

# --- Node definitions: ip | config_key | board_type | num_players | games_per_iter | selfplay_budget | eval_budget | lr | lr_schedule | train_lr_scheduler | train_window ---
# Proven hyperparameters: fixed LR 5e-5, no cosine scheduler
NODES=(
  "100.121.230.110|hex8_2p|hex8|2|100|200|128|5e-5|fixed|none|5|data/minimal_loop_gh200-8"
  "100.127.168.116|square8_2p|square8|2|100|128|128|5e-5|fixed|none|3|data/minimal_loop_square8_2p"
  "100.86.51.4|square8_3p|square8|3|200|128|128|5e-5|fixed|none|5|data/minimal_loop_square8_3p"
  "100.100.19.96|square8_4p|square8|4|200|128|128|5e-5|fixed|none|5|data/minimal_loop_square8_4p"
  "100.106.87.89|hex8_3p|hex8|3|100|128|128|5e-5|fixed|none|5|data/minimal_loop_hex8_3p"
  "100.98.19.73|hex8_4p|hex8|4|100|128|128|5e-5|fixed|none|5|data/minimal_loop_hex8_4p"
  "100.91.39.59|square19_2p|square19|2|50|128|128|5e-5|fixed|none|5|data/minimal_loop_square19_2p"
)

ONLY=""
DRY_RUN=false
RESTART=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --only) ONLY="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --restart) RESTART=true; shift ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

for entry in "${NODES[@]}"; do
  IFS='|' read -r ip config board np gpi sp_budget ev_budget lr lr_sched train_lr_sched tw workdir <<< "$entry"

  if [[ -n "$ONLY" && "$config" != "$ONLY" ]]; then
    continue
  fi

  echo "=== Deploying $config to $ip ==="

  # Generate training.conf
  TRAINING_CONF="# RingRift Training Loop Configuration — ${config}
# Auto-generated by deploy_training_service.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
TRAINING_MODEL=models/canonical_${config}.pth
TRAINING_WORK_DIR=${workdir}
TRAINING_BOARD_TYPE=${board}
TRAINING_NUM_PLAYERS=${np}
TRAINING_ITERATIONS=50
TRAINING_GAMES_PER_ITER=${gpi}
TRAINING_SELFPLAY_BUDGET=${sp_budget}
TRAINING_EVAL_BUDGET=${ev_budget}
TRAINING_LR=${lr}
TRAINING_LR_SCHEDULE=${lr_sched}
TRAINING_TRAIN_LR_SCHEDULER=${train_lr_sched}
TRAINING_TRAIN_WINDOW=${tw}
"

  if $DRY_RUN; then
    echo "  [dry-run] Would write training.conf:"
    echo "$TRAINING_CONF" | sed 's/^/    /'
    echo "  [dry-run] Would install ringrift-training.service and start it"
    continue
  fi

  # 1. Update code
  echo "  Updating code..."
  ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" \
    'cd ~/ringrift && git fetch origin && git checkout -f origin/main --detach 2>&1 | tail -1' || true

  # 2. Ensure logs directory exists
  ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" 'mkdir -p ~/ringrift/ai-service/logs'

  # 3. Stop existing training AND competing P2P/selfplay processes
  echo "  Stopping existing processes..."
  ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" '
    sudo systemctl stop ringrift-training 2>/dev/null || true
    sudo systemctl stop ringrift-p2p 2>/dev/null || true
    sudo systemctl disable ringrift-p2p 2>/dev/null || true
    pkill -9 -f minimal_alphazero_loop 2>/dev/null || true
    pkill -9 -f minimal_loop_supervisor 2>/dev/null || true
    pkill -9 -f p2p_orchestrator 2>/dev/null || true
    pkill -9 -f run_gpu_selfplay 2>/dev/null || true
    pkill -9 -f generate_gumbel_selfplay 2>/dev/null || true
    pkill -9 -f "selfplay.py" 2>/dev/null || true
    pkill -9 -f run_self_play_soak 2>/dev/null || true
  ' 2>/dev/null || true
  # Wait for GPU memory to free
  sleep 3

  # 4. Write training.conf
  echo "  Writing training.conf..."
  echo "$TRAINING_CONF" | ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" 'sudo tee /etc/ringrift/training.conf > /dev/null'

  # 5. Copy service file
  echo "  Installing service..."
  scp "${SSH_OPTS[@]}" "${AI_DIR}/${SERVICE_FILE}" "ubuntu@${ip}:/tmp/ringrift-training.service"
  ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" '
    sudo mv /tmp/ringrift-training.service /etc/systemd/system/ringrift-training.service
    sudo systemctl daemon-reload
    sudo systemctl enable ringrift-training
  '

  # 6. Start
  echo "  Starting service..."
  ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" 'sudo systemctl start ringrift-training'

  # 7. Verify
  sleep 2
  STATUS=$(ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" 'systemctl is-active ringrift-training 2>/dev/null' || echo "unknown")
  PID=$(ssh "${SSH_OPTS[@]}" "ubuntu@${ip}" 'pgrep -f minimal_alphazero_loop | head -1' 2>/dev/null || echo "none")
  echo "  Status: ${STATUS}, PID: ${PID}"

  if [[ "$STATUS" != "active" ]]; then
    echo "  WARNING: Service not active! Check with:"
    echo "    ssh ubuntu@${ip} 'sudo journalctl -u ringrift-training -n 30'"
  fi

  echo ""
done

echo "Done. Monitor with:"
echo "  ssh ubuntu@<ip> 'sudo journalctl -u ringrift-training -f'"
echo "  ssh ubuntu@<ip> 'sudo systemctl status ringrift-training'"
