#!/usr/bin/env python3
"""Pipeline Watchdog - Detect silent training failures before they waste GPU-hours.

Catches the 3 failure modes that wasted 120+ GPU-hours:
  1. Identical training data across iterations (no diversity)
  2. Training failing every iteration (loop retries broken command)
  3. Export failing every iteration (selfplay runs but produces nothing)

Usage:
    cd ~/ringrift/ai-service && export PYTHONPATH=.
    python scripts/pipeline_watchdog.py --mode minimal --work-dir data/minimal_loop
    python scripts/pipeline_watchdog.py --mode p2p
"""
from __future__ import annotations

import argparse, json, os, sqlite3, subprocess, sys, time, urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class Check:
    name: str
    passed: bool
    message: str
    severity: str = "FAIL"  # FAIL, WARN, OK


def _http_get(url: str, timeout: int = 10) -> dict | None:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.loads(r.read())
    except Exception:
        return None


def _query_db(path: str, sql: str, params: tuple = ()) -> list[dict]:
    if not Path(path).exists():
        return []
    try:
        conn = sqlite3.connect(path, timeout=5)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(sql, params).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except sqlite3.Error:
        return []


def _read_metrics(jsonl: Path, tail: int = 20) -> list[dict]:
    if not jsonl.exists():
        return []
    lines = jsonl.read_text().strip().split("\n")
    out = []
    for line in lines[-tail:]:
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            pass
    return out


def _npz_checksum(path: Path) -> float | None:
    try:
        import numpy as np
        # NPZ files here are trusted local training data generated by this project
        d = np.load(str(path), allow_pickle=True)
        return float(d["features"].sum())
    except Exception:
        return None


def _file_age_hours(path: Path) -> float | None:
    if not path.exists():
        return None
    return (time.time() - path.stat().st_mtime) / 3600.0


def _pgrep(pattern: str) -> bool:
    try:
        r = subprocess.run(["pgrep", "-f", pattern], capture_output=True, timeout=5)
        return r.returncode == 0
    except Exception:
        return False


def check_minimal(work_dir: Path, max_stale_h: float, min_success: float,
                  max_consec_fail: int) -> list[Check]:
    results = []
    metrics = _read_metrics(work_dir / "metrics.jsonl")

    # 1. Iteration progress
    if not metrics:
        results.append(Check("iteration_progress", False, "No metrics.jsonl entries found"))
    else:
        last = metrics[-1]
        try:
            ts = last.get("timestamp", "")
            age_h = (time.time() - datetime.fromisoformat(
                ts.replace("Z", "+00:00")).timestamp()) / 3600
        except Exception:
            age_h = float("inf")
        if age_h > max_stale_h:
            results.append(Check("iteration_progress", False,
                f"Last iteration {age_h:.1f}h ago (threshold: {max_stale_h}h)"))
        else:
            results.append(Check("iteration_progress", True,
                f"Iter {last.get('iteration', '?')} done {age_h:.1f}h ago, "
                f"elo~{last.get('estimated_elo', '?')}"))

    # 2. Data diversity — compare NPZ checksums
    npz_files = sorted(work_dir.glob("iter_*.npz"))[-5:]
    checksums = {f.name: _npz_checksum(f) for f in npz_files}
    checksums = {k: v for k, v in checksums.items() if v is not None}
    if len(checksums) >= 2:
        vals = list(checksums.values())
        dupes = sum(1 for i in range(1, len(vals)) if abs(vals[i] - vals[i - 1]) < 0.01)
        if dupes >= 2:
            results.append(Check("data_diversity", False,
                f"{dupes} consecutive identical NPZ checksums"))
        else:
            results.append(Check("data_diversity", True,
                f"{len(checksums)} NPZ files, checksums distinct"))
    else:
        results.append(Check("data_diversity", True,
            f"Only {len(checksums)} NPZ file(s)", severity="WARN"))

    # 3. Training success rate
    recent = metrics[-10:] if len(metrics) >= 3 else metrics
    if recent:
        successes = sum(1 for m in recent if m.get("training", {}).get("elapsed_s"))
        rate = successes / len(recent)
        consec_fail = 0
        for m in reversed(recent):
            if not m.get("training", {}).get("elapsed_s"):
                consec_fail += 1
            else:
                break
        if consec_fail >= max_consec_fail:
            results.append(Check("training_success", False,
                f"{consec_fail} consecutive training failures"))
        elif rate < min_success:
            results.append(Check("training_success", False,
                f"Success rate {rate:.0%} < {min_success:.0%}"))
        else:
            results.append(Check("training_success", True,
                f"Success rate {rate:.0%} ({successes}/{len(recent)})"))
    else:
        results.append(Check("training_success", False, "No metrics"))

    # 4. Export pipeline (selfplay OK but no training)
    if recent:
        export_fails = 0
        for m in reversed(recent):
            sp = m.get("selfplay", {})
            tr = m.get("training", {})
            if sp.get("completed", 0) > 0 and not tr.get("elapsed_s"):
                export_fails += 1
            else:
                break
        if export_fails >= max_consec_fail:
            results.append(Check("export_pipeline", False,
                f"{export_fails} iters: selfplay OK but training missing"))
        else:
            results.append(Check("export_pipeline", True, "Export flowing"))
    else:
        results.append(Check("export_pipeline", True, "No data", severity="WARN"))

    # 5. Resource waste
    wasted_s = sum(
        m.get("selfplay", {}).get("elapsed_s", 0)
        for m in metrics
        if m.get("selfplay", {}).get("completed", 0) > 0
        and not m.get("training", {}).get("elapsed_s")
    )
    wasted_h = wasted_s / 3600
    if wasted_h > 10:
        results.append(Check("resource_waste", False,
            f"{wasted_h:.1f} GPU-hours wasted (selfplay with no training)"))
    else:
        results.append(Check("resource_waste", True, f"{wasted_h:.1f}h wasted"))

    return results


def check_p2p(data_dir: Path, max_stale_h: float) -> list[Check]:
    results = []

    # 1. Infrastructure
    issues = []
    if not _pgrep("master_loop.py"):
        issues.append("master_loop down")
    if not _pgrep("p2p_orchestrator.py"):
        issues.append("p2p down")
    p2p = _http_get("http://localhost:8770/status")
    if p2p is None:
        issues.append("P2P unreachable")
    wq = _http_get("http://localhost:8770/work/status")
    if wq and wq.get("by_status", {}).get("pending", 0) > 500:
        issues.append(f"Queue backlog: {wq['by_status']['pending']} pending")
    if issues:
        results.append(Check("infrastructure", False, "; ".join(issues)))
    else:
        peers = p2p.get("alive_peers", "?") if p2p else "?"
        results.append(Check("infrastructure", True, f"Healthy, {peers} peers"))

    # 2. NPZ freshness
    training_dir = data_dir / "training"
    if training_dir.exists():
        npzs = list(training_dir.glob("*.npz"))
        stale = [f for f in npzs if (_file_age_hours(f) or 999) > 48]
        if stale and len(stale) == len(npzs):
            results.append(Check("data_freshness", False,
                f"All {len(npzs)} NPZ files >48h old"))
        else:
            results.append(Check("data_freshness", True,
                f"{len(npzs) - len(stale)}/{len(npzs)} fresh"))

    # 3. Model freshness
    canonical = list(Path("models").glob("canonical_*.pth")) if Path("models").exists() else []
    if canonical:
        ages = [(f.name, _file_age_hours(f) or 999) for f in canonical]
        freshest = min(ages, key=lambda x: x[1])
        if freshest[1] > 168:
            results.append(Check("promotions", False, "No model updated in 7+ days"))
        else:
            results.append(Check("promotions", True,
                f"Freshest: {freshest[0]} ({freshest[1]:.0f}h)"))

    return results


def print_report(results: list[Check]) -> bool:
    all_pass = all(r.passed for r in results)
    status = "ALL PASS" if all_pass else "FAILURES DETECTED"
    print(f"\n{'=' * 60}")
    print(f"  PIPELINE WATCHDOG: {status}")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'=' * 60}\n")
    for r in results:
        icon = "[OK]  " if r.passed else "[FAIL]"
        if r.passed and r.severity == "WARN":
            icon = "[WARN]"
        print(f"  {icon} {r.name:<25} {r.message}")
    fails = [r for r in results if not r.passed]
    print(f"\n  {len(results) - len(fails)}/{len(results)} checks passed")
    if fails:
        print(f"  FAILED: {', '.join(r.name for r in fails)}")
    print()
    return all_pass


def main():
    ap = argparse.ArgumentParser(description="Pipeline Watchdog")
    ap.add_argument("--mode", choices=["minimal", "p2p"], required=True)
    ap.add_argument("--work-dir", default="data/minimal_loop")
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--max-stale-hours", type=float, default=8.0)
    ap.add_argument("--min-training-success", type=float, default=0.5)
    ap.add_argument("--max-consecutive-failures", type=int, default=3)
    args = ap.parse_args()

    if args.mode == "minimal":
        results = check_minimal(
            Path(args.work_dir), args.max_stale_hours,
            args.min_training_success, args.max_consecutive_failures)
    else:
        results = check_p2p(Path(args.data_dir), args.max_stale_hours)

    all_pass = print_report(results)
    sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
