"""Utility modules for the AI service."""

from .memory_config import MemoryConfig
from .paths import (
    AI_SERVICE_ROOT,
    DATA_DIR,
    GAMES_DIR,
    SELFPLAY_DIR,
    METRICS_DIR,
    MODELS_DIR,
    LOGS_DIR,
    RUNS_DIR,
    PROMOTION_DIR,
    CONFIG_DIR,
    SCRIPTS_DIR,
    UNIFIED_ELO_DB,
    get_project_root,
    get_models_dir,
    get_data_dir,
    get_games_db_path,
    get_selfplay_db_path,
    get_model_path,
    get_log_path,
    ensure_dir,
    ensure_parent_dir,
)
from .json_utils import (
    JSONEncoder,
    dumps as json_dumps,
    dump as json_dump,
    pretty_dumps,
    json_default,
    load_json,
    save_json,
)
from .progress_reporter import (
    OptimizationProgressReporter,
    ProgressReporter,
    SoakProgressReporter,
)
from .load_throttle import (
    get_system_load,
    get_cpu_count,
    get_load_info,
    is_system_overloaded,
    wait_for_load_decrease,
    wait_for_load_decrease_async,
    LoadThrottler,
)
from .canonical_naming import (
    normalize_board_type,
    get_board_type_enum,
    make_config_key,
    parse_config_key,
    is_valid_board_type,
    get_all_config_keys,
    normalize_database_filename,
    CANONICAL_CONFIG_KEYS,
)
from .secrets import (
    mask_secret,
    mask_secret_prefix,
    sanitize_for_log,
    SecretString,
    load_secret_from_env,
    get_env_masked,
    is_sensitive_key,
)
from .yaml_utils import (
    load_yaml,
    load_yaml_with_defaults,
    safe_load_yaml,
    dump_yaml,
    dumps_yaml,
    load_config_yaml,
    validate_yaml_schema,
    YAMLLoadError,
)
from .checksum_utils import (
    compute_file_checksum,
    compute_bytes_checksum,
    compute_string_checksum,
    verify_file_checksum,
    compute_content_id,
    DEFAULT_CHUNK_SIZE,
    LARGE_CHUNK_SIZE,
)
from .datetime_utils import (
    utc_now,
    utc_timestamp,
    iso_now,
    iso_now_ms,
    to_iso,
    parse_iso,
    time_ago,
    format_duration,
    format_age,
    date_str,
    timestamp_str,
)
from .time_constants import (
    SECONDS_PER_MINUTE,
    SECONDS_PER_HOUR,
    SECONDS_PER_DAY,
    SECONDS_PER_WEEK,
    ONE_MINUTE,
    FIVE_MINUTES,
    TEN_MINUTES,
    FIFTEEN_MINUTES,
    THIRTY_MINUTES,
    ONE_HOUR,
    TWO_HOURS,
    SIX_HOURS,
    TWELVE_HOURS,
    ONE_DAY,
    ONE_WEEK,
    MS_PER_SECOND,
    DEFAULT_CACHE_TTL,
    DEFAULT_SYNC_INTERVAL,
    DEFAULT_TIMEOUT,
)
from .optional_imports import (
    NUMPY_AVAILABLE,
    TORCH_AVAILABLE,
    CUDA_AVAILABLE,
    MPS_AVAILABLE,
    AIOHTTP_AVAILABLE,
    PROMETHEUS_AVAILABLE,
    get_module,
    require_module,
    get_availability_summary,
)
from .env_config import (
    env,
    EnvConfig,
    get_str as env_get_str,
    get_int as env_get_int,
    get_float as env_get_float,
    get_bool as env_get_bool,
    get_list as env_get_list,
)
from .debug_utils import (
    timed,
    timed_async,
    log_call,
    debug_context,
    Timer,
    get_call_stack,
    format_exception_chain,
    memory_usage_mb,
    dump_state,
    DEBUG_ENABLED,
    PROFILE_ENABLED,
)
from .logging_utils import (
    PrefixedLogger,
    get_logger,
    LogContext,
    log_duration,
    log_duration_async,
    configure_logging,
    silence_logger,
)
from .result import (
    Result,
    Ok,
    Err,
    ResultError,
    result_from_exception,
    collect_results,
    partition_results,
    OperationResult,
)
from .file_utils import (
    atomic_write,
    write_atomic,
    read_safe,
    read_bytes_safe,
    file_exists,
    ensure_file_dir,
    backup_file,
    remove_safe,
    get_file_size,
    get_file_mtime,
)
from .assertions import (
    AssertionError as AssertionFailure,  # Rename to avoid shadowing builtin
    PreconditionError,
    PostconditionError,
    InvariantError,
    require,
    ensure,
    check,
    require_type,
    require_not_none,
    require_in_range,
    require_non_empty,
    unreachable,
    ASSERTIONS_ENABLED,
)
from .rate_limit import (
    Cooldown,
    RateLimiter,
    KeyedRateLimiter,
    rate_limit,
    rate_limit_async,
    RateLimitExceeded,
)

__all__ = [
    # Paths
    "AI_SERVICE_ROOT",
    "DATA_DIR",
    "GAMES_DIR",
    "SELFPLAY_DIR",
    "METRICS_DIR",
    "MODELS_DIR",
    "LOGS_DIR",
    "RUNS_DIR",
    "PROMOTION_DIR",
    "CONFIG_DIR",
    "SCRIPTS_DIR",
    "UNIFIED_ELO_DB",
    "get_project_root",
    "get_models_dir",
    "get_data_dir",
    "get_games_db_path",
    "get_selfplay_db_path",
    "get_model_path",
    "get_log_path",
    "ensure_dir",
    "ensure_parent_dir",
    # JSON utilities
    "JSONEncoder",
    "json_dumps",
    "json_dump",
    "pretty_dumps",
    "json_default",
    "load_json",
    "save_json",
    # Memory
    "MemoryConfig",
    "OptimizationProgressReporter",
    "ProgressReporter",
    "SoakProgressReporter",
    # Load throttling
    "get_system_load",
    "get_cpu_count",
    "get_load_info",
    "is_system_overloaded",
    "wait_for_load_decrease",
    "wait_for_load_decrease_async",
    "LoadThrottler",
    # Canonical naming
    "normalize_board_type",
    "get_board_type_enum",
    "make_config_key",
    "parse_config_key",
    "is_valid_board_type",
    "get_all_config_keys",
    "normalize_database_filename",
    "CANONICAL_CONFIG_KEYS",
    # Secrets handling
    "mask_secret",
    "mask_secret_prefix",
    "sanitize_for_log",
    "SecretString",
    "load_secret_from_env",
    "get_env_masked",
    "is_sensitive_key",
    # YAML utilities
    "load_yaml",
    "load_yaml_with_defaults",
    "safe_load_yaml",
    "dump_yaml",
    "dumps_yaml",
    "load_config_yaml",
    "validate_yaml_schema",
    "YAMLLoadError",
    # Checksum utilities
    "compute_file_checksum",
    "compute_bytes_checksum",
    "compute_string_checksum",
    "verify_file_checksum",
    "compute_content_id",
    "DEFAULT_CHUNK_SIZE",
    "LARGE_CHUNK_SIZE",
    # Datetime utilities
    "utc_now",
    "utc_timestamp",
    "iso_now",
    "iso_now_ms",
    "to_iso",
    "parse_iso",
    "time_ago",
    "format_duration",
    "format_age",
    "date_str",
    "timestamp_str",
    # Time constants
    "SECONDS_PER_MINUTE",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_DAY",
    "SECONDS_PER_WEEK",
    "ONE_MINUTE",
    "FIVE_MINUTES",
    "TEN_MINUTES",
    "FIFTEEN_MINUTES",
    "THIRTY_MINUTES",
    "ONE_HOUR",
    "TWO_HOURS",
    "SIX_HOURS",
    "TWELVE_HOURS",
    "ONE_DAY",
    "ONE_WEEK",
    "MS_PER_SECOND",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_SYNC_INTERVAL",
    "DEFAULT_TIMEOUT",
    # Optional imports
    "NUMPY_AVAILABLE",
    "TORCH_AVAILABLE",
    "CUDA_AVAILABLE",
    "MPS_AVAILABLE",
    "AIOHTTP_AVAILABLE",
    "PROMETHEUS_AVAILABLE",
    "get_module",
    "require_module",
    "get_availability_summary",
    # Environment configuration
    "env",
    "EnvConfig",
    "env_get_str",
    "env_get_int",
    "env_get_float",
    "env_get_bool",
    "env_get_list",
    # Debug utilities
    "timed",
    "timed_async",
    "log_call",
    "debug_context",
    "Timer",
    "get_call_stack",
    "format_exception_chain",
    "memory_usage_mb",
    "dump_state",
    "DEBUG_ENABLED",
    "PROFILE_ENABLED",
    # Logging utilities
    "PrefixedLogger",
    "get_logger",
    "LogContext",
    "log_duration",
    "log_duration_async",
    "configure_logging",
    "silence_logger",
    # Result pattern
    "Result",
    "Ok",
    "Err",
    "ResultError",
    "result_from_exception",
    "collect_results",
    "partition_results",
    "OperationResult",
    # File utilities
    "atomic_write",
    "write_atomic",
    "read_safe",
    "read_bytes_safe",
    "file_exists",
    "ensure_file_dir",
    "backup_file",
    "remove_safe",
    "get_file_size",
    "get_file_mtime",
    # Assertions
    "AssertionFailure",
    "PreconditionError",
    "PostconditionError",
    "InvariantError",
    "require",
    "ensure",
    "check",
    "require_type",
    "require_not_none",
    "require_in_range",
    "require_non_empty",
    "unreachable",
    "ASSERTIONS_ENABLED",
    # Rate limiting
    "Cooldown",
    "RateLimiter",
    "KeyedRateLimiter",
    "rate_limit",
    "rate_limit_async",
    "RateLimitExceeded",
]
