"""Utility modules for the AI service."""

from .memory_config import MemoryConfig
from .paths import (
    AI_SERVICE_ROOT,
    DATA_DIR,
    GAMES_DIR,
    SELFPLAY_DIR,
    METRICS_DIR,
    MODELS_DIR,
    LOGS_DIR,
    RUNS_DIR,
    PROMOTION_DIR,
    CONFIG_DIR,
    SCRIPTS_DIR,
    UNIFIED_ELO_DB,
    get_project_root,
    get_models_dir,
    get_data_dir,
    get_games_db_path,
    get_selfplay_db_path,
    get_model_path,
    get_log_path,
    ensure_dir,
    ensure_parent_dir,
)
from .json_utils import (
    JSONEncoder,
    dumps as json_dumps,
    dump as json_dump,
    pretty_dumps,
    json_default,
)
from .progress_reporter import (
    OptimizationProgressReporter,
    ProgressReporter,
    SoakProgressReporter,
)
from .load_throttle import (
    get_system_load,
    get_cpu_count,
    get_load_info,
    is_system_overloaded,
    wait_for_load_decrease,
    wait_for_load_decrease_async,
    LoadThrottler,
)
from .canonical_naming import (
    normalize_board_type,
    get_board_type_enum,
    make_config_key,
    parse_config_key,
    is_valid_board_type,
    get_all_config_keys,
    normalize_database_filename,
    CANONICAL_CONFIG_KEYS,
)
from .secrets import (
    mask_secret,
    mask_secret_prefix,
    sanitize_for_log,
    SecretString,
    load_secret_from_env,
    get_env_masked,
    is_sensitive_key,
)
from .yaml_utils import (
    load_yaml,
    load_yaml_with_defaults,
    safe_load_yaml,
    dump_yaml,
    dumps_yaml,
    load_config_yaml,
    validate_yaml_schema,
    YAMLLoadError,
)
from .checksum_utils import (
    compute_file_checksum,
    compute_bytes_checksum,
    compute_string_checksum,
    verify_file_checksum,
    compute_content_id,
    DEFAULT_CHUNK_SIZE,
    LARGE_CHUNK_SIZE,
)
from .datetime_utils import (
    utc_now,
    utc_timestamp,
    iso_now,
    iso_now_ms,
    to_iso,
    parse_iso,
    time_ago,
    format_duration,
    format_age,
    date_str,
    timestamp_str,
)

__all__ = [
    # Paths
    "AI_SERVICE_ROOT",
    "DATA_DIR",
    "GAMES_DIR",
    "SELFPLAY_DIR",
    "METRICS_DIR",
    "MODELS_DIR",
    "LOGS_DIR",
    "RUNS_DIR",
    "PROMOTION_DIR",
    "CONFIG_DIR",
    "SCRIPTS_DIR",
    "UNIFIED_ELO_DB",
    "get_project_root",
    "get_models_dir",
    "get_data_dir",
    "get_games_db_path",
    "get_selfplay_db_path",
    "get_model_path",
    "get_log_path",
    "ensure_dir",
    "ensure_parent_dir",
    # JSON utilities
    "JSONEncoder",
    "json_dumps",
    "json_dump",
    "pretty_dumps",
    "json_default",
    # Memory
    "MemoryConfig",
    "OptimizationProgressReporter",
    "ProgressReporter",
    "SoakProgressReporter",
    # Load throttling
    "get_system_load",
    "get_cpu_count",
    "get_load_info",
    "is_system_overloaded",
    "wait_for_load_decrease",
    "wait_for_load_decrease_async",
    "LoadThrottler",
    # Canonical naming
    "normalize_board_type",
    "get_board_type_enum",
    "make_config_key",
    "parse_config_key",
    "is_valid_board_type",
    "get_all_config_keys",
    "normalize_database_filename",
    "CANONICAL_CONFIG_KEYS",
    # Secrets handling
    "mask_secret",
    "mask_secret_prefix",
    "sanitize_for_log",
    "SecretString",
    "load_secret_from_env",
    "get_env_masked",
    "is_sensitive_key",
    # YAML utilities
    "load_yaml",
    "load_yaml_with_defaults",
    "safe_load_yaml",
    "dump_yaml",
    "dumps_yaml",
    "load_config_yaml",
    "validate_yaml_schema",
    "YAMLLoadError",
    # Checksum utilities
    "compute_file_checksum",
    "compute_bytes_checksum",
    "compute_string_checksum",
    "verify_file_checksum",
    "compute_content_id",
    "DEFAULT_CHUNK_SIZE",
    "LARGE_CHUNK_SIZE",
    # Datetime utilities
    "utc_now",
    "utc_timestamp",
    "iso_now",
    "iso_now_ms",
    "to_iso",
    "parse_iso",
    "time_ago",
    "format_duration",
    "format_age",
    "date_str",
    "timestamp_str",
]
